/**
 * @file regression.h
 * @brief Baseline comparison and regression detection for CI performance gating
 * 
 * Provides functionality to load baseline metrics from JSON files,
 * compare current run metrics against baselines, and detect performance regressions.
 */

#ifndef REGRESSION_H
#define REGRESSION_H

#include <stdint.h>
#include <stdbool.h>
#include "metrics.h"

/* Default regression threshold (10%) */
#define REGRESSION_THRESHOLD_DEFAULT 0.10

/* Exit code for regression detection */
#define EXIT_REGRESSION 2

/* Exit code for configuration mismatch */
#define EXIT_CONFIG_MISMATCH 4

/**
 * @brief Baseline metrics extracted from JSON file
 */
typedef struct {
    double pkts_processed_per_sec;  /* Packets per second throughput */
    double mbps_processed;          /* Megabytes per second throughput */
    uint64_t latency_p95_ns;        /* 95th percentile latency in nanoseconds */
    double drop_rate;               /* Drop rate (0.0 - 1.0) */
    
    /* Additional baseline data for reporting */
    uint64_t pkts_processed;        /* Total packets processed */
    uint64_t bytes_processed;       /* Total bytes processed */
    uint64_t queue_drops;           /* Total queue drops */
    uint64_t capture_drops;         /* Total capture drops */
    double elapsed_sec;             /* Elapsed time in seconds */
    
    /* Metadata for compatibility validation */
    metrics_metadata_t metadata;    /* Captured configuration metadata */
    
    bool valid;                     /* Whether baseline was successfully loaded */
} regression_baseline_t;

/**
 * @brief Regression comparison results
 */
typedef struct {
    /* Throughput comparison */
    double baseline_pps;
    double current_pps;
    double pps_delta_pct;           /* Negative = regression */
    bool pps_regression;
    
    /* Bandwidth comparison */
    double baseline_mbps;
    double current_mbps;
    double mbps_delta_pct;          /* Negative = regression */
    bool mbps_regression;
    
    /* Latency comparison */
    uint64_t baseline_p95_ns;
    uint64_t current_p95_ns;
    double latency_delta_pct;       /* Positive = regression */
    bool latency_regression;
    
    /* Drop rate comparison */
    double baseline_drop_rate;
    double current_drop_rate;
    double drop_delta_pct;          /* Positive = regression */
    bool drop_regression;
    
    /* Overall result */
    bool any_regression;
    double threshold;               /* Threshold used for comparison */
} regression_result_t;

/**
 * @brief Load baseline metrics from a JSON file
 * 
 * Parses a JSON metrics file (generated by --metrics-json) and extracts
 * the relevant baseline values for comparison.
 * 
 * @param filepath Path to the baseline JSON file
 * @param baseline Pointer to baseline structure to populate
 * @return 0 on success, -1 on error
 */
int regression_load_baseline(const char *filepath, regression_baseline_t *baseline);

/**
 * @brief Compare current metrics against baseline
 * 
 * Performs regression detection by comparing current run metrics
 * against the loaded baseline using the specified threshold.
 * 
 * @param baseline Loaded baseline metrics
 * @param current Current metrics snapshot
 * @param threshold Regression threshold (e.g., 0.10 for 10%)
 * @param result Pointer to result structure to populate
 * @return 0 on success, -1 on error
 */
int regression_compare(const regression_baseline_t *baseline,
                       const metrics_snapshot_t *current,
                       double threshold,
                       regression_result_t *result);

/**
 * @brief Print regression comparison report
 * 
 * Outputs a human-readable report of the regression comparison results.
 * 
 * @param result Regression comparison results
 */
void regression_print_report(const regression_result_t *result);

/**
 * @brief Check if any regression was detected
 * 
 * @param result Regression comparison results
 * @return true if any regression detected, false otherwise
 */
bool regression_detected(const regression_result_t *result);

/**
 * @brief Validate baseline metadata compatibility
 * 
 * Checks that the baseline was captured under compatible conditions.
 * Validates interface, filter, threads, and OS match current settings.
 * 
 * @param baseline Loaded baseline with metadata
 * @param current_meta Current run metadata
 * @param error_msg Buffer to write error message (if incompatible)
 * @param error_msg_len Length of error_msg buffer
 * @return true if compatible, false if mismatch detected
 */
bool regression_validate_metadata(const regression_baseline_t *baseline,
                                  const metrics_metadata_t *current_meta,
                                  char *error_msg, size_t error_msg_len);

#endif /* REGRESSION_H */
